#!/bin/bash

version="0.2.1"
usage="usage $(basename $0) <COMMAND> [SUBCOMMAND] [ARGS...]
COMMANDS:
    help                                display this menu
    (init | initialize)                 initialize environment
    (mod | module) <SUBCOMMAND>         perform module operations
    (proc | process) <SUBCOMMAND>       perform process operations
    (repo | repository) <SUBCOMMAND>    perform repository operations
    (var | variable) <SUBCOMMAND>       perform variable operations
    version                             print application version"

# initialize instance variables - set scripterdir if not already set
export scriptdir="$(pwd)/$(dirname $0)/sbin"

[ -z "$scripterdir" ] && scripterdir="$HOME/.local/share/scripter"
export logdir="$scripterdir/log"
export moddir="$scripterdir/modules"
export procfile="$scripterdir/procfile"
export repofile="$scripterdir/repofile"
export varfile="$scripterdir/varfile"

# execute command
case "$1" in
    help)
        echo "$usage"
        ;;
    init|initialize)
        # create scripter directories
        [ ! -d $scripterdir ] && mkdir $scripterdir
        [ ! -d $logdir ] && mkdir $logdir
        [ ! -d $moddir ] && mkdir $moddir
        [ ! -f $procfile ] && touch $procfile
        [ ! -f $repofile ] && touch $repofile
        [ ! -f $varfile ] && touch $varfile
        ;;
    mod|module)
        $scriptdir/module.sh ${@:2}
        ;;
    proc|process)
        $scriptdir/process.sh ${@:2}
        ;;
    repo|repository)
        $scriptdir/repository.sh ${@:2}
        ;;
    var|variable)
        $scriptdir/variable.sh ${@:2}
        ;;
    version)
        echo "v$version"
        ;;
    *)
        echo "$usage"
        exit 1
        ;;
esac
