#!/bin/bash

USAGE="USAGE $(basename $0) [COMMAND]
COMMANDS:
    help                                display this menu
    (init | initialize)                 initialize scripter environment
    (mod | module) <SUBCOMMAND>         perform module operations
    (proc | process) <SUBCOMMAND>       perform process operations
    (var | variable) <SUBCOMMAND>       perform variable operations"

# load project directory and file configurations
PROJECTDIR="$(pwd)/$(dirname $0)/.."
. $PROJECTDIR/sbin/config.sh

# execute command
case "$1" in
    help)
        printf "$USAGE\n"
        exit 0
        ;;
    init|initialize)
        # create modules and log directories
        [ ! -d $MODDIR ] && mkdir $MODDIR
        [ ! -d $LOGDIR ] && mkdir $LOGDIR
        [ ! -f $PROCFILE ] && touch $PROCFILE
        [ ! -f $VARFILE ] && touch $VARFILE
        ;;
    mod|module)
        $0-module.sh ${@:2}
        ;;
    proc|process)
        $0-process.sh ${@:2}
        ;;
    var|variable)
        $0-variable.sh ${@:2}
        ;;
    *)
        printf "$USAGE\n"
        exit 1
        ;;
esac
