#!/bin/bash

usage="usage $(basename $0) [COMMAND]
COMMANDS:
    help                                display this menu
    (init | initialize)                 initialize environment
    (mod | module) <SUBCOMMAND>         perform module operations
    (proc | process) <SUBCOMMAND>       perform process operations
    (repo | repository) <SUBCOMMAND>    perform repository operations
    (var | variable) <SUBCOMMAND>       perform variable operations"

# load project directory and file configurations
projectdir="$(pwd)/$(dirname $0)/.."
. $projectdir/sbin/config.sh

# execute command
case "$1" in
    help)
        printf "$usage\n"
        exit 0
        ;;
    init|initialize)
        # create modules and log directories
        [ ! -d $moddir ] && mkdir $moddir
        [ ! -d $logdir ] && mkdir $logdir
        [ ! -f $procfile ] && touch $procfile
        [ ! -f $repofile ] && touch $repofile
        [ ! -f $varfile ] && touch $varfile
        ;;
    mod|module)
        $0-module.sh ${@:2}
        ;;
    proc|process)
        $0-process.sh ${@:2}
        ;;
    repo|repository)
        $0-repository.sh ${@:2}
        ;;
    var|variable)
        $0-variable.sh ${@:2}
        ;;
    *)
        printf "$usage\n"
        exit 1
        ;;
esac
